# Name of the domain bridge, used for node naming and logging
# robot_1_ID: 213
# robot_2_ID: 214
# robot_3_ID: 215
# server : 217
name: domain_bridge

topics:
  amcl_pose:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    from_domain: 213
    to_domain: 217
    remap: amcl_pose_1
  amcl_pose:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    from_domain: 214
    to_domain: 217
    remap: amcl_pose_2
  amcl_pose:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    from_domain: 215
    to_domain: 217
    remap: amcl_pose_3


  task_completion:
    type: task_msgs/msg/TaskCompletion
    from_domain: 213
    to_domain: 217

  task_completion:
    type: task_msgs/msg/TaskCompletion
    from_domain: 214
    to_domain: 217

  task_completion:
    type: task_msgs/msg/TaskCompletion
    from_domain: 215
    to_domain: 217


  allocate_task_213:
    type: task_msgs/srv/AllocateTask
    from_domain: 217
    to_domain: 213
  
  allocate_task_214:
    type: task_msgs/srv/AllocateTask
    from_domain: 217
    to_domain: 214

  allocate_task_215:
    type: task_msgs/srv/AllocateTask
    from_domain: 217
    to_domain: 215


